--テーブル初期化
DROP TABLE IF EXISTS public.m_user_team;
DROP TABLE IF EXISTS public.t_join_user;
DROP TABLE IF EXISTS public.m_user;

DROP TABLE IF EXISTS public.m_post;
DROP TABLE IF EXISTS public.m_team;
DROP TABLE IF EXISTS public.t_file;
DROP TABLE IF EXISTS public.t_log;
DROP TABLE IF EXISTS public.t_exclusive_control;

--役職マスタ作成
CREATE TABLE public.m_post (
    post_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_name character varying(20) NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer DEFAULT 1 NOT NULL
);

ALTER TABLE IF EXISTS public.m_post
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.m_post FROM justinuser;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.m_post TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.m_post TO postgres;


--所属マスタ作成
CREATE TABLE public.m_team (
    team_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name character varying(20) NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer DEFAULT 1 NOT NULL
);

ALTER TABLE IF EXISTS public.m_team
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.m_team FROM justinuser;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.m_team TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.m_team TO postgres;

--役職の初期値
INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'代表取締役',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'専務取締役',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'取締役',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'マネージャー',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'エクスパート',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'リーダー',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_post (
post_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'なし',
current_timestamp  , 
current_timestamp ,
'AdiminTest01');

--所属の初期値
INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'役員',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'第１流通チーム',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'第２流通チーム',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'自治体チーム',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'総務',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'本社',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'SESチーム',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'試用期間者',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'契約社員',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'組織に属さない',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

INSERT INTO m_team (
team_name, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'なし',
current_timestamp , 
current_timestamp ,
'AdiminTest01');

--ユーザーマスタ作成
CREATE TABLE public.m_user (
    user_id character varying(20) PRIMARY KEY,
    post_id integer NOT NULL,
    user_name character varying(100) NOT NULL,
    user_name_kana character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    role integer NOT NULL,
    retirement_flg integer DEFAULT 0 NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    FOREIGN KEY(post_id) REFERENCES m_post(post_id)
);

ALTER TABLE IF EXISTS public.m_user
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.m_user FROM justinuser;
GRANT SELECT, INSERT, UPDATE ON TABLE public.m_user TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.m_user TO postgres;

--ユーザーの初期値
INSERT INTO m_user(
user_id,
post_id,
user_name,
user_name_kana,
password,
role,
first_create_date,
last_modified_date,
last_modified_user)
VALUES (
'AdminTest01',
1,
'管理者ユーザー',
'カンリシャユーザー',
'$2a$10$Mrh1F8X7FKamLdHlGVAhQu2Jf2k0X.0n53FOLX2ltCeFIlei9NYjm',
1,
current_timestamp , 
current_timestamp ,
'AdiminTest01');


--所属管理マスタ作成
CREATE TABLE public.m_user_team (
    user_id character varying(20) NOT NULL,
    team_id integer NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer DEFAULT 1 NOT NULL,
	PRIMARY KEY (user_id, team_id),
    FOREIGN KEY(user_id) REFERENCES m_user(user_id),
    FOREIGN KEY(team_id) REFERENCES m_team(team_id)
);

ALTER TABLE IF EXISTS public.m_user_team
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.m_user_team FROM justinuser;
GRANT INSERT, SELECT, UPDATE ON TABLE public.m_user_team TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.m_user_team TO postgres;

--所属管理マスタの初期値
INSERT INTO m_user_team (
user_id,
team_id, 
first_create_date, 
last_modified_date, 
last_modified_user) 
VALUES (
'AdminTest01',
1,
current_timestamp , 
current_timestamp ,
'AdiminTest01');

--ファイル管理作成
CREATE TABLE public.t_file (
    file_id integer GENERATED BY DEFAULT AS IDENTITY,
    serial_number integer,
    file bytea,
    file_name character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    date character varying(8) NOT NULL,
    delete_flg integer DEFAULT 0 NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer DEFAULT 1 NOT NULL,
	PRIMARY KEY (file_id, serial_number)
);

ALTER TABLE IF EXISTS public.t_file
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.t_file FROM justinuser;
GRANT INSERT, SELECT, UPDATE ON TABLE public.t_file TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.t_file TO postgres;


--会議参加者作成
CREATE TABLE IF NOT EXISTS public.t_join_user(
    file_id integer NOT NULL,
	serial_number integer NOT NULL,
    user_id character varying(20) NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20)  NOT NULL,
    version integer NOT NULL DEFAULT 1,
	PRIMARY KEY (file_id, serial_number, user_id),
    FOREIGN KEY(file_id,serial_number) REFERENCES t_file(file_id,serial_number),
    FOREIGN KEY(user_id) REFERENCES m_user(user_id)
);

ALTER TABLE IF EXISTS public.t_join_user
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.t_join_user FROM justinuser;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.t_join_user TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.t_join_user TO postgres;


--排他ロック作成
CREATE TABLE IF NOT EXISTS public.t_exclusive_control(
    host_name character varying(100) NOT NULL,
    screen_id character varying(100) NOT NULL,
    file_id integer,
    user_id character varying(20),
    team_id integer,
    post_id integer,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer NOT NULL DEFAULT 1
);

ALTER TABLE IF EXISTS public.t_exclusive_control
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.t_exclusive_control FROM justinuser;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.t_exclusive_control TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.t_exclusive_control TO postgres;


--ログ作成
CREATE TABLE IF NOT EXISTS public.t_log(
    log_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_section integer NOT NULL,
    operation_content character varying(2000) NOT NULL,
    message_code character varying(100) NOT NULL,
    incident_class_name character varying(50) NOT NULL,
    incident_date timestamp without time zone NOT NULL,
    first_create_date timestamp without time zone NOT NULL,
    last_modified_date timestamp without time zone NOT NULL,
    last_modified_user character varying(20) NOT NULL,
    version integer NOT NULL DEFAULT 1
);

ALTER TABLE IF EXISTS public.t_log
    OWNER to postgres;

--ユーザー権限付与
REVOKE ALL ON TABLE public.t_log FROM justinuser;
GRANT SELECT, INSERT, UPDATE ON TABLE public.t_log TO justinuser;
--管理者権限付与
GRANT ALL ON TABLE public.t_log TO postgres;